donations/urls.py
from django.conf.urls import include, url
from donations import views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
"""inventory_app URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

app_name = 'donations'
# For use with class based generic views
urlpatterns = [
    url(r'^new_user/$', views.CreateUserView.as_view(), name='new_user'),
    url(r'^event(?P<pk>\d+)$', views.EventDetailsView.as_view(), name='event_details'),
    url(r'^event$', views.CreateEventView.as_view(), name='create_event'),
    url(r'^donor$', views.DonorInfoView.as_view(), name='donor_info'),
    url(r'^donation$', views.DonationDetailsView.as_view(), name='donation_details'),
<<<<<<< Updated upstream
=======
    url(r'eventlist$', views.event_list, name='eventlist'),
    url(r'addtocart+$', views.add_to_cart, name='add_to_cart'),
    url(r'added/(?P<event_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'cart_details', views.cart_details, name='cart_details'),
    url(r'cart_remove/(?P<event_id>\d+)/$', views.cart_remove, name='cart_remove'),
    #url(r'^cart$'),
>>>>>>> Stashed changes
]
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ngo/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import url
from donations import urls
from donations import views
from django.urls import path, include

# For use with class based generic views
urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', views.EventListView.as_view(), name='list_events'),
    url(r'^event$', views.CreateEventView.as_view(), name='create_event'),
    url(r'', include(urls, namespace="donations")),
    path('usr/', include('users.urls')),

    #url(r'accounts/', include(('django.contrib.auth.urls', 'django_accounts'), namespace="django_accounts")),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from . import views as users_views
from django.contrib.auth import views as auth_views

app_name = 'users'


urlpatterns = [
    path('home', users_views.home, name='home-page'),
    path('register/', users_views.register, name='register-page'),
    path('profile/', users_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login-page'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout-page'),
    # format for adding admin exclusive views below
    path('check/', users_views.admin_view, name='checking'),
    path('usr_view/', users_views.usr_view, name='usr_view'),
]

donations/models.py
from django.db import models
<<<<<<< Updated upstream
from django.utils import timezone
from django.contrib.auth.models import User
from django.forms.widgets import SelectDateWidget


# # Create your models here.
# # class Product(models.Model):
# #     name = models.CharField(max_length=20)
# #     price = models.IntegerField()
# #     image = models.ImageField(upload_to='images', default=None, null=True, blank=True)
# #
# #     # you can call save() from Model class to save Product
# #
# #     def __str__(self):
# #         return self.name
=======
from users.models import User
from decimal import Decimal
from django.conf import settings
>>>>>>> Stashed changes


class Donor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    CMA_num = models.IntegerField(null=False, blank=False)
    phone = models.CharField(max_length=40, null=False, blank=False)
    address = models.CharField(max_length=100, null=False, blank=False)
    city = models.CharField(max_length=40, null=False, blank=False)
    state = models.CharField(max_length=40, null=False, blank=False)
    zip_code = models.CharField(max_length=40, null=False, blank=False)
    country = models.CharField(max_length=40, null=False, blank=False)
    urbanization = models.CharField(max_length=40, null=True, blank=True)
    date = models.DateField(auto_now=True)


class DonationDetails(models.Model):
    class Meta:
        constraints = [models.UniqueConstraint(fields=['donor', 'donation_type'], name='unique_donation')]

    donor = models.ForeignKey('Donor', on_delete=models.CASCADE)
    donation_type = models.CharField(max_length=40, null=False, blank=False)
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)


class Events(models.Model):
    name = models.CharField(max_length=40, null=False, blank=False)
    date = models.DateField(null=False, blank=False)


class Cart(object):
    def __init__(self, request):
        self.session = request.session
        cart = self.session.get(settings.CART_SESSION_ID)
        if not cart:
            cart = self.session[settings.CART_SESSION_ID] = {}
        self.cart = cart

    def __iter__(self):

        event_ids = self.cart.keys()
        events = Events.objects.filter(id__in=event_ids)
        for event in events:
            self.cart[str(event.id)]['event'] = event

        for value in self.cart.values():
            value['amount'] = Decimal(value['amount'])
            yield value

    def add(self, event, amount):
        event_id = str(event.id)
        if event_id not in self.cart:
            self.cart[event_id]={'amount': amount}
        self.save()

    def remove(self, event):
        event_id = str(event.id)
        if event_id in self.cart:
            del self.cart[event_id]
            self.save()

    def save(self):
        self.session[settings.CART_SESSION_ID] = self.cart
        self.session.modified = True

donations/forms.py
from .models import Donor
from .models import DonationDetails
from .models import Events
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class DonorForm(forms.ModelForm):
    class Meta:
        model = Donor
        fields = ('CMA_num', 'phone', 'address', 'city', 'state', 'zip_code', 'country', 'urbanization')


class DonationDetailsForm(forms.ModelForm):
    class Meta:
        model = DonationDetails
        fields = '__all__'


class EventForm(forms.ModelForm):
    class Meta:
        model = Events
        fields = ('name', 'date')


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

donations/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
<<<<<<< Updated upstream
=======
from django.views.generic.base import View
from django.forms import modelformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
>>>>>>> Stashed changes
from donations.models import Donor
from donations.models import DonationDetails
from donations.models import Events
from donations.forms import DonorForm
from donations.forms import DonationDetailsForm
from donations.forms import EventForm
from donations.forms import CreateUserForm
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_POST
from .models import Cart
from django.contrib.auth.decorators import login_required


# Generic class based views here.
class EventListView(ListView):
    model = Events
    template_name = 'events.html'


class EventDetailsView(DetailView):
    model = Events
    template_name = 'event_details.html'


class DonorInfoView(CreateView):
    model = Donor
    template_name = 'donor_info.html'
    form_class = DonorForm

    def get_success_url(self):
        return reverse('donations:donation_details')


class DonationDetailsView(CreateView):
    model = DonationDetails
    template_name = 'donation_details.html'
    form_class = DonationDetailsForm

    def get_success_url(self):
        return reverse('donations:cart')


class CreateEventView(CreateView):
    model = Events
    template_name = 'create_event.html'
    form_class = EventForm

    def get_success_url(self):
        return reverse('donations:event_details', args=[self.object.id])

class CreateUserView(CreateView):
    model = User
    form_class = CreateUserForm
    template_name = 'new_user.html'
    # fields = ('username', 'password', 'first_name', 'last_name', 'email')

    def get_success_url(self):
        return reverse('list_events')
<<<<<<< Updated upstream
=======

@login_required
def event_list(request):
    eventlist = Events.objects.all()
    # form = DonationDetailsForm
    context = {'events': eventlist}

    return render(request, 'donations/eventslist.html', context)


@require_POST
def cart_add(request, event_id):
    cart = Cart(request)
    #print(request.POST.get('event_id'))
    event = get_object_or_404(Events, id=event_id)
    amount = request.POST.get('amount')
    # amount = float(amount)
    #print(amount)
    try:
        amount = float(amount)
        cart.add(event = event, amount = amount)
    except:
        cart.add(event=event, amount=0)
    return redirect('donations:cart_details')


def cart_remove(request, event_id):
    cart = Cart(request)
    #print('*******')
    print(event_id)

    #event = get_object_or_404(Events, id=request.POST.get('event_id'))
    event = get_object_or_404(Events, id=event_id)
    print(event)
    cart.remove(event)
    return redirect('donations:cart_details')


def cart_details(request):
    cart = Cart(request)
    return render(request, 'donations/detail.html', {'cart': cart})


def add_to_cart(request):
    context = {'event_id': request.POST.get('event_id'), 'amount':  request.POST.get('amount')}
    return render(request, 'donations/cart.html', context)




>>>>>>> Stashed changes

donations/templates/donations/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>DOne here!!</p>
{% for event in event_id %}
<p>{{event}}</p>
{% endfor %}




</body>
</html>

donations/templates/donations/create_event.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Event</title>
    <h2>Enter Event Details</h2>
</head>
<body>
  <form method='post' class="EventForm" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class='save button'>Save</button>
  </form>
  <br>
  <a href="/">Back</a>
</body>
</html>

donations/templates/donations/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for event in cart %}


    <p>****************</p>

    <p>****************</p>
    <p>{{event.event.name}}</p>
    <p>{{event.amount}}</p>
    <p>{{event.event.id}}</p>

<a href="{% url 'donations:cart_remove' event.event.id %}" class="btn">Remove From Cart</a>
{% endfor %}

<a href="{% url 'donations:eventlist' %}" class="btn">Back to list</a>
</body>
</html>

donations/templates/donations/donation_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Donation Details</title>
    <h2>Enter your donation specifications</h2>
</head>
<body>
  <form method='post' class="DonationDetailsForm" enctype="multipart/form-data">
  {% csrf_token %}
<<<<<<< Updated upstream
  {{ form.as_p }}
  <button type="submit" class='save button'>Save</button>
=======
  {{ event_formset.management_form }}
  {% for form in event_formset %}
      <div class="ro form-row spacer">
          <div class="col-2">
              <label>{{form.amount.label}}</label>
          </div>
          <div class="col-4">
              <div class="input-group">
                  {{form.amount}}
              </div>
          </div>
      </div>
      <br>
  {% endfor %}
  <div class="row spacer">
      <div class="col-4 offset-2">
          <button type="submit" class="btn btn-block btn-primary", name="saving">Save</button>
          <button type="submit" class="btn btn-block btn-primary", name="addingtocart", formaction="{% url 'donations:add_to_cart' %}">Add to Cart</button>

      </div>
  </div>
>>>>>>> Stashed changes
  </form>
</body>
</html>

donations/templates/donations/donor_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Donor Information</title>
    <h2>Enter your personal information</h2>
</head>
<body>
  <form method='post' class="DonorForm" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class='save button'>Save</button>
  </form>
  <br>
  {# <a href="{% url 'donations:event_details' object.id %}">Back</a> #}
  <a href="/">Cancel</a>
</body>
</html>

donations/templates/donations/event_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event Details</title>
    <h2>Event Details</h2>
</head>
<body>
    {% load static %}
    Event: {{object.name}} <br>
    Date: {{object.date}} <br>
    <br>
    <a href="{% url 'donations:donor_info' %}">Donate Today!</a>
    <br>
    <br>
    <a href="/">Back</a>
</body>
</html>

donations/templates/donations/events.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make a Donation</title>
    <h2>Make a Donation</h2>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="../../../static/css/basic.css">
</head>
<body>

<div id="header">
    {% block header %}
        {% if user.username %}
            <p>Hello User: {{ user.username }}| <a href="{% url 'users:profile' %}?next={{request.path}}">Profile</a> | <a href="{% url 'users:logout-page' %}?next={{request.path}}">Logout</a></p>
        {% else %}
            <p><a href="{% url 'users:login-page' %}">Login</a> | <a href="{% url 'donations:new_user' %}">Sign Up</a> </p>
        {% endif %}
    {% endblock %}
</div>

 Upcoming Events: <br>
 {% for event in object_list %}
    <a href="{% url 'donations:event_details' event.id %}">{{event.name}}</a>&nbsp;&nbsp;&nbsp;&nbsp;
 {% endfor %}
 <br>
 <br>
 {% if user.is_authenticated %}
    <a href="{% url 'donations:donor_info' %}">Donate Today!</a><br><br>
 {% endif %}
 {% if user.is_admin %}
    <a href="{% url 'donations:create_event' %}">New Event</a><br><br>
 {% endif %}
</body>
</html>

donations/templates/donations/eventslist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
On the page to see the events!!!


<div>
<a href="{% url 'users:usr_view'  %}" class="btn">Back to Profile</a>
</div>
{% for event in events %}
<form action="{% url 'donations:cart_add' event.id %}" method="post">
  {% csrf_token %}

    <p>{{event.id}}</p>
    <p>{{event.name}}</p>

    <label for="amount">Amount:</label>
    <input type="number" min = "0" id="amount" name="amount"><br><br><br>
    <input type="submit" value="Add to cart">
    <a href="{% url 'donations:cart_remove' event.id %}" class="btn">Remove From Cart</a>
</form>
{% endfor %}

</body>
</html>

donations/templates/donations/make_donation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make a Donation</title>
    <h2>Make a Donation</h2>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="../../../static/css/basic.css">
</head>
<body>
{% comment %}
<div id="header">
    {% block header %}
        {% if user.username %}
            <p>Hello User: {{ user.username }} | <a href="{% url 'django_accounts:logout' %}?next={{request.path}}">Logout</a></p>
        {% else %}
            <p><a href="{% url 'django_accounts:login' %}?next={{request.path}}">Login</a> | <a href="{% url 'donations:new_user' %}">Sign Up</a> </p>
        {% endif %}
    {% endblock %}
</div>
{% endcomment %}

 {% for donation_type in object_list %}
    <a href="{% url 'donations:product_details' product.id %}">{{donation_type}}</a>&nbsp;&nbsp;&nbsp;&nbsp;
 {% endfor %}
 <br>

{% comment %}
{% if user.is_authenticated %}
    <a href="{% url 'productapp:new_product' %}">New Product</a><br><br>
{% endif %}
{% endcomment %}
</body>
</html>

donations/templates/donations/new_user.html
{% extends "users/base.html" %}
<h2>Create A New Account</h2>
{% block content %}
  <form method='post' class="CreateUserForm">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class='save button'>Save</button>
  </form>
  <br>
  <a href="/">Back</a>
{% endblock content %}


{% block side1link %}"/"{% endblock side1link %}
{% block side1 %}Home{% endblock side1 %}

{% block side2link %}"/usr/login/"{% endblock side2link %}
{% block side2 %}Login{% endblock side2 %}

donations/templates/donations/order_projects.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>